version: "2"
services:
  nginx:
    links:
    - php
    image: svutpala/nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    links:
    - mysql
    image: svutpala/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./code:/code
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  varnish:
    image: million12/varnish
    ports:
      - "80:80"
    links:
      - nginx
      - php

